#!/bin/bash

#==================================== help ====================================#

usage() {
    echo -e "Usage: $0"
    echo -e "\t-n <name of pbs job>"
    echo -e "\t-s <path/to/pbs/script>"
    echo -e "\t[-c <path/to/run/config/file>]"
    echo -e "\t[-x <path/to/executable>]"
    echo -e "\t[-i <path/to/initial/location/file>]"
}

#======================== parse command line arguments ========================#

while getopts ":hs:c:i:n:x:" opt; do
    case $opt in
        h)
            usage
            exit 0
            ;;
        n)
            JOB_NAME=$OPTARG
            ;;
        s)
            PBS_SCRIPT=$OPTARG
            ;;
        c)
            RUN_CONF=$OPTARG
            ;;
        x)
            EXE_FILE=$OPTARG
            ;;
        i)
            INIT_POS=$OPTARG
            ;;
        *)
            echo "Error: Invalid arguments!"
            usage
            exit 1
            ;;
    esac
done
shift $((OPTIND-1))

#=============================== validate input ===============================#

if [ -z $JOB_NAME ]; then
    echo "Error: Job name must be supplied!"
    exit 1
fi

if [ -z $PBS_SCRIPT ]; then
    echo "Error: Path to PBS scrit must be supplied!"
    exit 1
elif [ ! -f $PBS_SCRIPT ]; then
    echo "Error: PBS script path is invalid!"
    exit 1
fi

if [ -z $RUN_CONF ]; then
    RUN_CONF=runConfig.txt
elif [ ! -f $RUN_CONF ]; then
    echo "Error: Run config file path is invalid!"
    exit 1
fi

if [ -z $EXE_FILE ]; then
    EXE_FILE=SphereSimulator.X
elif [ ! -f $EXE_FILE ]; then
    echo "Error: Executable file path is invalid!"
    exit 1
fi

if [ ! -f $INIT_POS ]; then
    echo "Error: Intial position file path is invalid!"
    exit 1
fi

#============================= set up directories =============================#

# record current directory
CURRDIR=`pwd`

# create a direcotry name using jobname and current time
WORKDIR="/scratch/shravan_flux/saibalde/"$JOB_NAME"_"`date +%Y-%m-%d_%H-%M-%S`

# create the directory under scratch filesystem
mkdir $WORKDIR

#================================= copy stuff =================================#

cp $PBS_SCRIPT $WORKDIR/jobsub.pbs
cp $RUN_CONF $WORKDIR/runConfig.txt
cp $EXE_FILE $WORKDIR/SphereSimulator.X
if [ -n "$INIT_POS" ]; then
    cp $INIT_POS $WORKDIR/posInitial.txt
fi

#================================= run script =================================#

cd $WORKDIR
qsub -N $JOB_NAME jobsub.pbs
cd $CURRDIR

